### ISSUE TITLE
Quitting to the main menu does not reset the music played.

### ISSUE THREAD

**Issue by FantaX1911** [P3D-Legacy/P3D-Legacy#11]
when you quit to the main menu, whatever the music that was playing before just keeps running like you never quit.

**Comment by FantaX1911** [comment]
it's not just the main menu, changing maps doesn't change music.

**Comment by CaptainSegis** [comment]
Unable to repro anymore, please confirm

**Comment by dsbilling** [comment]
Probably fixed by #56
