### ISSUE TITLE
Weirdness with catch location data on Pokemon Menu Screen

### ISSUE THREAD

**Issue by darkfire006** [P3D-Legacy/P3D-Legacy#14]
The Location and method get merged in a weird way instead of one after the other

**Comment by nilllzz** [comment]
![image](https://user-images.githubusercontent.com/2119926/37169292-d99ed9da-2307-11e8-9f22-6e7091317a0a.png)
Has this been fixed?
Seems fine to me.

**Comment by CaptainSegis** [comment]
Fixed long ago
