### ISSUE TITLE
@Pokemon.AddToStorage does not allow box id 10 and above

### ISSUE THREAD

**Issue by jianmingyong** [P3D-Legacy/P3D-Legacy#15]
Though I don't normally mention all these little flaws but since this was part of my edit before I left, some stuff were left in broken state.

The logic isn't really perfect and has a flaw in it. It doesn't resolve the command parameter correctly hence it only support up to 9.
 
It is easy to fix if you understand the logic, the boilerplate code is already available there. Just need to change the command parameter processing part to read the correct tokens and apply the correct number and it should work just fine.

If you want to remove it, feel free then.

**Comment by CaptainSegis** [comment]
Probably fixed, please confirm.
