### ISSUE TITLE
[BUG] Pokégear not opening via controller.

### ISSUE THREAD

**Issue by Lexichu** [P3D-Legacy/P3D-Legacy#161]
**Describe the bug**
Pressing Y on Xbox controllers (or their remapped equals) does not open the Pokégear.

**To Reproduce**
Have an Xbox controller.
Press Y.
The Pokégear will not open.

**Expected behavior**
The Pokégear should open.

**Screenshots**
[N/A]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.59.1

**Additional context**
[n/a]

**Comment by JappaWakka** [comment]
The Pokégear can now be opened using the select/back button. For some reason, the Y button doesn't work. Multiple game devs have complained about this problem so this is the best solution for now.
