### ISSUE TITLE
[BUG] Softlock when pausing during animations

### ISSUE THREAD

**Issue by Lexichu** [P3D-Legacy/P3D-Legacy#162]
**Describe the bug**
Pausing the game during certain animations will cause the game to softlock.

**To Reproduce**
1: Go into a battle.
2: Throw a Pokéball at a wild Pokémon.
3: During this animation (between the text box saying the ball was thrown, and the textbox saying the catch result) pause the game by alt-tabbing, pressing Escape, pressing Start, losing window focus on the game, etc..
Note: This may also apply to other combat animations. May require further testing.

**Expected behavior**
Ideally: Animation should stop, and resume as expected once the game is unpaused.
Alternatively: Animation duration timer continues whilst paused, but does not finish until unpaused. Animation cuts to end once the timer reaches 0.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.59.1

**Additional context**

**Comment by darkfire006** [comment]
531137c157c47f9ce1a09beeeb0790307d6fabb0
FINV
