### ISSUE TITLE
[BUG] Cerulean Diglett "ceruleandiglett" text box.

### ISSUE THREAD

**Issue by Lexichu** [P3D-Legacy/P3D-Legacy#163]
**Describe the bug**
A Diglett in the house that was broken into by a Rocket in Gen I of Pokémon has a Diglett that literally just says "ceruleandiglett".

**To Reproduce**
1: ...talk to the Diglett in Cerulean City, behind Misty's gym.

**Expected behavior**
The Diglett should play its Pokémon cry whilst saying something like "Diglett: Dig."
Also suggest a rare chance it says "Diglett: ceruleandiglett".

**Screenshots**
[ https://drive.google.com/file/d/11_513TdVlKQo_gpeVSpoErq7vGfvcrDa/view ]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.59.1

**Additional context**
Add any other context about the problem here, like for example a crash log.

**Comment by darkfire006** [comment]
cceea5684b67a38ef0a8e8d13fdcffd28640bceb
issue resolved
