### ISSUE TITLE
[BUG] Missing shiny sprites

### ISSUE THREAD

**Issue by AlexCorruptor** [P3D-Legacy/P3D-Legacy#168]
**Describe the bug**
Most of the Shiny Pokemon for Gen 6 don't have their Summary sprites different from the normal ones

**To Reproduce**
1. Encounter/Hatch/Evolve any Gen 6 Pokemon
2. Check the Summary screen and notice the main Pokemon sprite

**Expected behavior**
Expected to see shiny sprites within the summary/PC screens

**Screenshots**
Examples: Greninja, Amaura and Yveltal
![image](https://user-images.githubusercontent.com/102594443/187150704-6832cf3c-c771-427f-b5f9-6186213f8b96.png)
![amaura](https://user-images.githubusercontent.com/102594443/187150860-3d379704-d25b-481b-a645-2b1043a8da0f.png)
![yveltal](https://user-images.githubusercontent.com/102594443/187150995-9137aa63-f5c3-482a-ba5b-c9507e90d6e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Version: 0.59.1

**Additional context**
NON

**Comment by JappaWakka** [comment]
Fixed in next version
