### ISSUE TITLE
[BUG] The game is crashing on startup

### ISSUE THREAD

**Issue by Lufims** [P3D-Legacy/P3D-Legacy#169]
**Describe the bug**
When I try to open the game it crashes

**To Reproduce**
1. Open the game

**Expected behavior**
Open the game

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/73536178/187254236-c3a2a6b4-0ebe-4a42-a416-ec03ee500a56.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional
 - Version 7

**Additional context**
I think it might be my "gpu" or chipset, it only supports opengl 1.4 and not completely directx 9 i think it's 97% of directx 9 support or something

**Comment by darkfire006** [comment]
The game is nolonger supported for older versions of windows, we recommend updating to Windows 10 or 11
