### ISSUE TITLE
Crashing right away

### ISSUE THREAD

**Issue by Grumlenz** [P3D-Legacy/P3D-Legacy#17]
as soon as i open the pokemon 3D application it instantly crashes any idea why ????/

**Comment by connedbrews** [comment]
One likely cause is missing software requirements. Make sure you have OpenAL and .NET Framework installed and try again.

**Comment by Grumlenz** [comment]
OpenAL says that it doesnt have the administrator permissions but it does i run it as admin just says i dont so idk :/

**Comment by dsbilling** [comment]
@Grumlenz Did you resolve the issue?
