### ISSUE TITLE
[QoL] Send hold item to the bag when releasing a Pokémon

### ISSUE THREAD

**Issue by RoyalGuard1991** [P3D-Legacy/P3D-Legacy#173]
(Tested in Indev 0.59.2)

**Is your feature request related to a problem? Please describe.**
I sometimes release Pokémon when I see no more use to them, and on occasion I've noticed that I forget to remove hold items from said Pokémon I release, which causes the hold item to be outright deleted.

**Describe the solution you'd like**
When a Pokémon is released via the PC while holding an item, it would be nice to have the hold item return to the player's bag (assuming there is enough room for the bag to hold it). The player can already dispose of items by selling them at stores, or toss them directly from the bag itself, so hold items being deleted when a Pokémon is released comes off as both redundant and inconvenient if you do it accidentally.

**Describe alternatives you've considered**
If this is somehow too difficult to implement, perhaps maybe implement a warning pop up when the player tries to release a Pokémon holding an item, that states if they continue with releasing the Pokémon, the hold item will be lost and that they should consider removing it, and have a yes/no choice to continue.

**Additional context**
Upon further research, the QoL I am suggesting appears to have be adopted by official Pokémon games as of Sword and Shield, and all future games since.

**Comment by JappaWakka** [comment]
Just implemented this. Thank you for submitting this issue. I've also made the item icons visible for Pokémon that are in a pc box.
