### ISSUE TITLE
Question regarding supported OS.

### ISSUE THREAD

**Issue by FrostKnight** [P3D-Legacy/P3D-Legacy#206]
What is the oldest windows OS that you have used to make this game work? And if so, can you tell me what I would need to make it work for me, etc...

**Comment by dsbilling** [comment]
> What is the oldest windows OS that you have used to make this game work? And if so, can you tell me what I would need to make it work for me, etc...

We have documented this here: [https://wiki.pokemon3d.net/index.php/Pok%C3%A9mon_3D#Requirements](https://wiki.pokemon3d.net/index.php/Pok%C3%A9mon_3D#Requirements)

**Comment by FrostKnight** [comment]
> > What is the oldest windows OS that you have used to make this game work? And if so, can you tell me what I would need to make it work for me, etc...
> 
> We have documented this here: https://wiki.pokemon3d.net/index.php/Pok%C3%A9mon_3D#Requirements

Do you know of  a place where I can DL dotnet 4.8 for anything older than windows 10? For example, windows 7.

I have a VM, but cannot remember if its x86 or 64 bit.

**Comment by dsbilling** [comment]
> > > What is the oldest windows OS that you have used to make this game work? And if so, can you tell me what I would need to make it work for me, etc...
> > 
> > 
> > We have documented this here: [wiki.pokemon3d.net/index.php/Pok%C3%A9mon_3D#Requirements](https://wiki.pokemon3d.net/index.php/Pok%C3%A9mon_3D#Requirements)
> 
> Do you know of a place where I can DL dotnet 4.8 for anything older than windows 10? For example, windows 7.
> 
> I have a VM, but cannot remember if its x86 or 64 bit.

You should be able to google your way to an official download. Feel free to join our Discord server if you have any questions or need more help.

**Comment by FrostKnight** [comment]
Yeah, I have tried searching for an official download, but each time I think I succeeded, I find out, I failed.

Btw, no one should use google, its a terrible search engine that globs ads on people, does mass surveillance, hurts the environment, etc...

I wish people would stop saying google it for these reasons.
