### ISSUE TITLE
The game should check for dependencies

### ISSUE THREAD

**Issue by dsbilling** [P3D-Legacy/P3D-Legacy#22]
The game should check for dependencies like the launcher does, since the launcher isn't used anymore.

Check this for reference:
https://github.com/P3D-Legacy/P3D-Legacy-Launcher/blob/master/P3D-Legacy%20Launcher/Forms/MainForm.cs#L136

**Comment by JappaWakka** [comment]
OpenAL isn't required anymore but I understand what you mean

**Comment by darkfire006** [comment]
no longer requires any dependancies and can be run without any outside installs, we can reopen if that ever changes
