### ISSUE TITLE
"Pokemon3d.exe has stopped working"

### ISSUE THREAD

**Issue by Vleaso** [P3D-Legacy/P3D-Legacy#23]
I have this problem, where whenever I try to start the P3D launcher, it brings up the Monogame loading screen, then says "Pokemon3d.exe has stopped working". 

I've already downloaded all the programs that was said to be required for the game (XNA, Microsoft Visual Studio, MonoGame 3.6). I can't figure out what's wrong. 
Can someone help me out?

**Comment by FantaX1911** [comment]
you need to install OpenAL
https://www.openal.org/downloads/oalinst.zip
