### ISSUE TITLE
Pokémon sprites too small for display boxes, not centered in the box

### ISSUE THREAD

**Issue by TheTechnician27** [P3D-Legacy/P3D-Legacy#27]
Here's an image of the issue I'm referring to. I wasn't sure what else to call the box, but the Pokémon isn't centered and is too small for the box, giving it an awkward appearance. This happens with Cyndaquil and Chikorita as well.

![rename totodile](https://user-images.githubusercontent.com/12673964/52690581-bf382780-2f23-11e9-9e07-610e062045aa.png)

**Comment by TheOmegaGhost** [comment]
As per suggestion, PokemonImageView sprites have better scaling and positioning starting next update.
