### ISSUE TITLE
Music stops during battles

### ISSUE THREAD

**Issue by TheTechnician27** [P3D-Legacy/P3D-Legacy#29]
For whatever reason, the music can become disabled completely in the middle of a battle, leaving only the sound effects, such as damage noises. This lack of music persists until you restart the program. It's happened to me three times – each time during a wild encounter, I'm fairly certain – and it's been seemingly random for two of the three times. The other one happened right after my Pokemon ate a berry, though this may be coincidental.

**Comment by Robovh** [comment]
I have that too, pretty sad, i like the music

**Comment by jianmingyong** [comment]
#34 This may do the trick.

**Comment by Lyraedan** [comment]
Hello, I see this issue still persists and would like to lend a hand, I am a programmer myself. Perhaps I could find a solution

**Comment by DanielRTRD** [comment]
> Hello, I see this issue still persists and would like to lend a hand, I am a programmer myself. Perhaps I could find a solution

Look thru the code and see if you can find the bug. When you have create a PR for a fix. Thanks! :)

**Comment by darkfire006** [comment]
> Hello, I see this issue still persists and would like to lend a hand, I am a programmer myself. Perhaps I could find a solution

Hi Lyraeden, there is actually a PR currently open and being refined that will likely have a solution for this. Thank you for your interest though!
