### ISSUE TITLE
[Soft-lock] Unable to escape Menu -> Options -> Advanced

### ISSUE THREAD

**Issue by TheTechnician27** [P3D-Legacy/P3D-Legacy#30]
I can still navigate the arrow back and forth from the 'Back' button to the 'Reset Options' button, but trying to actually go back by using the button doesn't work. Neither the gamepad nor the mouse will trigger the 'Back' button, and so the program has to be restarted. I don't know how to replicate this.

Edit: I'm also not certain if this applies to all Menu -> Options -> X, but I don't see why it wouldn't.

Edit 2: I just got it to work again on Menu -> Options -> Graphics. I can change all of the settings, but all of the buttons are greyed out, and the 'Back' button doesn't work. I still have no idea how to replicate this, but it's probably relatively easy based on how quickly it happened again.

Edit 3: I've added an image, but stretching and compressing the window makes the sliders and buttons move out of sync with each other. I'm unsure if this is an independent issue, but I'll test it after I've restarted P3D. As can be seen in the screenshot, the buttons and sliders are faded out, but they can still be used like normal, except 'Back'.

![scale](https://user-images.githubusercontent.com/12673964/53293093-0bd8f980-3793-11e9-9c89-90e01ba074cd.png)

**Comment by dsbilling** [comment]
Seems like this issue is from 0.55.2, but I can replicate it in 0.57.1. When having the game in a small window and then maximizing it this issue occurs.

**Comment by dsbilling** [comment]
Cannot replicate in latest release.
