### ISSUE TITLE
Crashes on Lapras on Start cutscene [BUG]

### ISSUE THREAD

**Issue by Tangled0902** [P3D-Legacy/P3D-Legacy#76]
It Crashes When Lapras is on Screen in The Opening Cutscene It Does So every time.

**Comment by darkfire006** [comment]
Is this an issue in 0.58.1 release?
Can you provide a crash log? (these are found in the same folder as the game exe)

**Comment by dsbilling** [comment]
Closing this, reopen it if there is any more info on the issue.
