### ISSUE TITLE
Buying out Zinc from Safari Zone Shop Causes Crash

### ISSUE THREAD

**Issue by connedbrews** [P3D-Legacy/P3D-Legacy#8]
Happens with release Indev 0.54.2, and suspected to happen in latest build.

Link to report thread, contains all the details: http://pokemon3d.net/forum/threads/16926/

**Comment by nilllzz** [comment]
I cannot confirm this.

**Comment by FantaX1911** [comment]
I cannot confirm this either.

**Comment by nilllzz** [comment]
Remind me if the new item screen is in a public release already?

**Comment by FantaX1911** [comment]
it is, and after some more testing, I can actually confirm this bug and it's only happening to zink when you try to buy all of the inventory at once.

**Comment by nilllzz** [comment]
Probably happens when you buy out whatever the last item in the store is.

**Comment by CaptainSegis** [comment]
Fixed
