### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by ghost** [P3D-Legacy/P3D-Legacy#84]
Hi

Is there a manual somewhere? Since the forum is closed too, I have some questions

- how do you move? The arrows keys don't work. 

- what are the other keys?

- how do i switch to full screen?

**Comment by dsbilling** [comment]
Check out the wiki: [https://wiki.pokemon3d.net/index.php/Main_Page](https://wiki.pokemon3d.net/index.php/Main_Page)
