### ISSUE TITLE
Update to latest Monogame

### ISSUE THREAD

**Issue by ghost** [P3D-Legacy/P3D-Legacy#85]
hi

I see not the latest version of Monogame is used. MonoGame 3.8 is latest.
Why not?

**Comment by dsbilling** [comment]
Current release of the game was released a few months before the MonoGame 3.8, so there where not much time for us to add that support. Although it might be added for next release.

**Comment by ghost** [comment]
Maybe it could be usefull to try to locate the code parts that currently prevent to make a linux/mac version too, in order to replace them with other code or exclusively use monogame code?
It would also be fantastic to have in the end a iOS/Android version since monogame supports it too!

MonoGame website says this:

 Cross-Platform

We currently support iOS, Android, MacOS, Linux, all Windows platforms, PS4, PSVita, Xbox One, and Switch with more platforms on the way.

**Comment by JappaWakka** [comment]
https://gist.github.com/neilt6/6d07322070470536ea0ba409c343c2a5
https://gist.github.com/neilt6/287cc804a42b20f1973c9435ceec2686
Someone wrote some implementations for Naudio for ios and android, but the thing is... A LOT of the code is written with windows in mind so it's not just a flip of a switch to fix it.

**Comment by JappaWakka** [comment]
Also... What does the latest version of monogame offer other than being a later version?

**Comment by ghost** [comment]
Let me change the question: what does the older monogame offer which the latest version doesn't offer and you don't want to upgrade for that?

You can just use monogame for playing audio on Windows, Linux, Mac, Android and iOS (and some game consoles): https://gamefromscratch.com/monogame-tutorial-audio/
So if you already use monogame, it makes no sense to use Naudio and re-invent the wheel.

From that tutorial:
"If you are on MacOS or Linux, you want to stick to the simplified audio API that we demonstrated earlier."

**Comment by dsbilling** [comment]
@lonely-unicorn Feel free to create a PR for adding support for other operating systems.

**Comment by ghost** [comment]
I am not a developer :-)

**Comment by ghost** [comment]
Are you guys serious about maintaining this project?
Because when you can't even update some of the dependencies of your own project...
I basically gave you all what you need in that tutorial.

**Comment by Aragas** [comment]
This is an open-source project where we always welcome new contributors.
There are no benefits of upgrading the project to MonoGame 3.8 in a hurry. The current version we use is not the reason we are limited to Windows.
We are still waiting for MonoGame to resolve some issues we have with the audio, and when I was checking the release notes, the necessary changes weren't there unfortunately.

**Comment by dsbilling** [comment]
> Are you guys serious about maintaining this project? Because when you can't even update some of the dependencies of your own project... I basically gave you all what you need in that tutorial.

Yes, we are serious about maintaining this project. Currently, we do not see a big benefit of updating Monogame to the latest version based on you just saying we should. There is a big process we have to go through to do this, also this has to pass QA. We will proceed with an update of the dependency when we see it fit for this project. We do not need a tutorial for updating Monogame, but thanks for linking it. 

Please read the [Code of Conduct](https://github.com/P3D-Legacy/P3D-Legacy/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guide](https://github.com/P3D-Legacy/P3D-Legacy/blob/master/CONTRIBUTING.md)

**Comment by ghost** [comment]
There are no audio issues in monogame just to play a background music or sound effect you use.
There are made 100s of games using monogame. Nobody has a problem except you guys 👎

**Comment by ghost** [comment]
And further: the reason the project can't work on linux and mac are you guys too.
Monogame is by definition for all platforms, but you guys did the incredible job to break this 👎

**Comment by Aragas** [comment]
We're sorry you feel that way! From what I know, you can use Wine to run the game on Linux!

**Comment by ghost** [comment]
Why are you limited to windows? I really don't understand.

**Comment by dsbilling** [comment]
> Why are you limited to windows? I really don't understand.

Pokémon 3D is using Monogame as its middleware/engine, with the .NET framework as the class library. The main issue is that the entire game is designed with Windows facilities and libraries in mind, so it would take a lot to make it work on other platforms.

**Comment by ghost** [comment]
What libraries you mean? And why are they even used since monogame has everything you need according to their website.
The original developer had a strange point of view. Monogame was created to have one engine for everything you need in a game.

**Comment by dsbilling** [comment]
> What libraries you mean? And why are they even used since monogame has everything you need according to their website. The original developer had a strange point of view. Monogame was created to have one engine for everything you need in a game.

The game did not use Monogame at first release, it used XNA. Then some years later (many years ago) it jumped over to Monogame since XNA was deprecated. A lot of the code for this game is soon to be 10 years old. So to make this work with the latest and the greatest is a hard and cumbersome task to do. We want to, believe me, but it won't happen anytime soon since it will take a lot of manpower to do so.

**Comment by JappaWakka** [comment]
> And further: the reason the project can't work on linux and mac are you guys too. Monogame is by definition for all platforms, but you guys did the incredible job to break this 👎

I'd watch your tone if I were you.

**Comment by FrostKnight** [comment]
It's a shame you cannot port this to python, that is truly cross-platform.
Although that would be a hell of a lot of work, work I cannot ever even think of doing, aka, I also am not a developer.

That being said, I understand why you said this, peace all, I hope someday an alternative arrives. 

Btw, when I said I only wanted offline, on some level, I also just would want 721, gen 6 changes, same story, same TM list,  doesn't even have to be 3D, just has to be as reliable as pokemon polished crystal's latest beta is, with all the interesting changes you have regarding pokemon added, etc...

And of course, be usable on linux.  

If you cannot, do not sweat it, no worries...

I still haven't figured out how to get it running in wine tho...

;)

Then again, haven't tried since 2020, so maybe it works now. 

Anywho, hope all works out for you all!
